name: rtdl-num-embeddings-package
channels:
- https://conda.anaconda.org/conda-forge
- nodefaults
dependencies:
- flit=3.9.0
- jupyterlab<5
- mypy=1.11.1
- numpy=1.19.5
- pdoc=14.4.0
- pip<25
- pytest=8.3.2
- python=3.8
- pytorch=1.8.0
- scikit-learn=1.0.2
- ruff=0.5.7
- tomli=2.0.1
- tqdm=4.66.1
- xdoctest=1.1.6
- pip:
  - delu==0.0.23
  - rtdl_revisiting_models==0.0.2
